/* SHARED CONSTANTS */
export const TOGGLE_CLICK = 'TOGGLE_CLICK';


/* ToDO CONSTANTS */
export const CREATE_TODO = 'CREATE_TODO';
export const DELETE_TODO = 'DELETE_TODO';
export const DELETE_ALL_TODO = 'DELETE_ALL_TODO';
export const GET_ALL_TODO = 'GET_ALL_TODO';
export const CHANGE_STATUS = 'CHANGE_STATUS';
